import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme";
import { SidebarComp } from "@/components/examples/sidebar";
import "../globals.css";
import "@sihaxito/deluxe-ui/styles.css";
import { Navbar } from "@/components/examples/navbar";
import { SidebarContextProvider } from "@/components/sidebar-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarContextProvider>
            <div>
              <div className="grid flex-1 items-start md:grid-cols-[auto_minmax(0,1fr)]">
                <SidebarComp />
                <div className="w-full">
                  <Navbar />
                  {children}
                </div>
              </div>
              <footer className="border-t bg-neutral-800 p-4">
                Deluxe UI :p
              </footer>
            </div>
          </SidebarContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
