import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/providers/theme";
import { SidebarComp } from "../components/sidebar";
import "./globals.css";
import "@sihaxito/deluxe-ui/styles.css";
import { Navbar } from "../components/navbar";
import { SidebarContextProvider } from "../components/sidebar-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarContextProvider>
            <div className="border-b">
              <div className="duration-[400ms] flex-1 items-start md:grid md:grid-cols-[auto_minmax(0,1fr)]">
                <SidebarComp />
                <div className="w-full">
                  <Navbar />
                  {children}
                </div>
              </div>
            </div>
          </SidebarContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
