import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme";
import { SidebarComp } from "@/components/sidebar";
import "../globals.css";
import "@sihaxito/deluxe-ui/styles.css";
import { Navbar } from "@/components/navbar";
import { SidebarContextProvider } from "@/components/sidebar-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarContextProvider>
            
              <div className="flex-1 items-start">
                  <Navbar />
                {/* <div className="h-[calc(100vh-4rem)] md:gap-10 grid md:grid-cols-[auto_minmax(0,1fr)]">
                <SidebarComp />
                  {children}
                </div> */}
                {children}
                {/* <footer className="h-16 px-4 py-2 border-t bg-neutral-50 dark:bg-neutral-900 dark:border-neutral-800">MUEJEJE</footer> */}
              </div>
          </SidebarContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
